### ISSUE TITLE
Error occurred while running npm run serve

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-common#1] opened 2018-12-07 18:23 UTC
```
TypeError: t.provider[e] is not a function
    at t._promise (/opt/os.js/node_modules/@osjs/common/dist/main.js:44:7447)
    at t.signalDependenciesReady (/opt/os.js/node_modules/@osjs/common/dist/main.js:7:5601)
    at /opt/os.js/node_modules/@osjs/common/dist/main.js:7:4162
```

**Comment by andersevenrud** [comment] 2018-12-08 22:01
Thanks!

This was actually caused by an issue with the dbus service provider. Closing.

**Closed as completed by andersevenrud** 2018-12-08 22:01 UTC
Labels: wontfix
